default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: piotool_db
  password: piotool_db

development:
  <<: *default
  database: piotool_development

test:
  <<: *default
  database: piotool_test

production:
  <<: *default
  database: piotool_production
